spring.application.name=bot-repasse
server.port=8080

# Mapeamento do Telegram
bot.telegram.token=${TELEGRAM_BOT_TOKEN}
bot.telegram.channel-id=${TELEGRAM_CHANNEL_ID}

# Mapeamento do WhatsApp
bot.whatsapp.destination-id=${WHATSAPP_DESTINATION_ID}